# SPDX-FileCopyrightText: 2021 onwards Martin Häuer
# SPDX-License-Identifier: CC0-1.0
#
# find a HowTo Guide here: <https://github.com/OPEN-NEXT/OKH-LOSH/blob/master/sample_data/okh-TEMPLATE-HOWTO.md>
#
okhv = "OKH-LOSHv1.0" # NOT to be changed
name = "your-awesome-OSH"
repo = "https://gitlab.com/YOU/your-awesome-project/"
version = "1.0.0"
release = "https://gitlab.com/YOU/your-awesome-project/-/releases/vX.X.X"
license = "the-SPDX-ID"
licensor = "xxx"
organization = "xxx"
readme = "README.md"
contribution-guide = "CONTRIBUTING.md"
image = "xxx.jpg"
documentation-language = "en-GB"
technology-readiness-level = "OTRL-3"
documentation-readiness-level = "ODRL-3"
attestation = "https://certification.oshwa.org/cl000001.html"
publication = "https://doi.org/10.1371/journal.pone.0193087"
function = "xxx"
standard-compliance = "DIN EN 1335"
cpc-patent-class = "D03D 35/00"
tsdc = "MEC"
bom = "BoM.csv"
manufacturing-instructions = "/Documentation/Assembly_Guide/AssemblyGuide.md"
user-manual = "/Documentation/User_Guide/UserGuide.md"

[[outer-dimensions]]
openSCAD = "cube(size = [400,350,150])"
unit = "mm"

[[part]]
name = "your-awesome-part"
image = "xxx.jpg"
tsdc = "3DP"
source = "xxx.scad"
export = [
  "xxx.pdf",
  "xxx.stl"
]

[[part.outer-dimensions]]
openSCAD = "cube(size = [120,100,3])"
unit = "mm"

[[software]]
release = "https://github.com/arduino/ArduinoCore-mbed/releases/tag/1.3.2"
installation-guide = "https://github.com/arduino/ArduinoCore-mbed/blob/a2c06d768f5ebb6821ae6505b2032ee58f4ef70d/README.md"
