okhv = "OKH-LOSHv1.0"
name = "your-awesome-OSH"
repo = "https://gitlab.com/xxx"
version = "1.0.0"
release = "https://gitlab.com/xxx"
license = "the-SPDX-ID"
licensor = "xxx"
organisation = "xxx"
readme = "README.md"
image = "xxx.jpg"
documentation-language = "en-GB"
technology-readiness-level = "OTLR-5"
documentation-readiness-level = "ODLR-4"
attestation = "https://certification.oshwa.org/cl000001.html"
function = "xxx"
standard-compliance = "DIN EN 1335"
cpc-patent-class = "get CPC-ID from here <https://worldwide.espacenet.com/classification> e.g. D03D 35/00"
tsdc = "MEC"
bom = "BoM.csv"
manufacturing-instructions = "/Documentation/Assembly_Guide/AssemblyGuide.md"
user-manual = "/Documentation/User_Guide/UserGuide.md"
outer-dimension-dim = "mm"
outer-dimension = "cube(size = [400,350,150]"

[[part]]
name = "your-awesome-part"
image = "xxx.jpg"
tsdc = "3DP"
source = "xxx.scad"
export = [
  "xxx.pdf",
  "xxx.stl"
]
material = "PLA"
outer-dimension-dim = "mm"
outer-dimension = "cube(size = [120,100,3]"

[[software]]
release = "https://github.com/arduino/ArduinoCore-mbed/releases/tag/1.3.2"
installation-guide = "https://github.com/arduino/ArduinoCore-mbed/blob/a2c06d768f5ebb6821ae6505b2032ee58f4ef70d/README.md"