okhv = "OKH-LOSHv1.0"
name = "OHLOOM"
repo = "https://gitlab.com/OSEGermany/ohloom"
version = "0.10.0"
release = "https://gitlab.com/OSEGermany/ohloom/-/tags/ohloom-0.10.0"
license = "CC-BY-SA-4.0"
licensor = "Jens Meisner"
organization = "OSE Germany e.V."
readme = "README.md"
image = "/Documentation/User_Guide/User_Guide.jpg"
documentation-language = "en-GB"
technology-readiness-level = "OTRL-5"
documentation-readiness-level = "ODRL-5"
function = "The Open Hardware Loom is a simple, hand-operated weaving loom made of wood, screws and 3D printed plastic pieces for the most part. It is simple to make and operate."
cpc-patent-class = "D03D 35/00"
tsdc = "MEC"
bom = "sBoM.csv"
manufacturing-instructions = "/Documentation/Assembly_Guide/AssemblyGuide.md"
user-manual = "/Documentation/User_Guide/UserGuide.md"
fabric-width-mm = 400

[[outer-dimensions]]
openSCAD = "cube(size = [400,350,150])"
unit = "mm"

[[part]]
name = "Clamp Ring"
image = "/Documentation/Assembly_Guide/Parts_Print_2.jpg"
tsdc = "3DP"
source = "/3DParts/ClampRing/ClampRing.scad"
export = [
  "/3DParts/ClampRing/ClampRing.pdf",
  "/3DParts/ClampRing/ClampRing.stl"
]
printing-process = "FDM"
material = "ABS"
mass-g = 30
infill = 30
raft-brim = true
supports = false
resolution-mm = 0.2
shell-thickness = 3
top-bottom-thickness = 3

[[part.outer-dimensions]]
openSCAD = "cylinder(h=30, r=28)"
unit = "mm"

[[part]]
name= "CombModul"
image = "Documentation/Assembly_Guide/Parts_Print_3.jpg"
tsdc = "3DP"
source = "/3DParts/CombModul/CombModul.scad"
export = [
  "/3DParts/CombModul/CombModul.pdf",
  "/3DParts/CombModul/CombModul.stl"
]
printing-process = "FDM"
material = "PLA"
mass-g = 30
infill = 30
raft-brim = true
supports = false
resolution-mm = 0.27
shell-thickness = 3
top-bottom-thickness = 3

[[part.outer-dimensions]]
openSCAD = "cube(size = [120,100,5]"
unit = "mm"

[[part]]
name = "PoleBase"
tsdc = "3DP"
source = "/3DParts/PoleBase/PoleBase.scad"
export = "/3DParts/PoleBase/PoleBase.stl"
printing-process = "FDM"
material = "PLA"
mass-g = 85
infill = 30
raft-brim = true
supports = false
resolution-mm = 0.3
shell-thickness = 3
top-bottom-thickness = 4

[[part.outer-dimensions]]
openSCAD = "cube(size = [130,115,100]"
unit = "mm"

[[part]]
name = "RatchetPawl"
image = "Documentation/Assembly_Guide/Parts_Print_4.jpg"
tsdc = "3DP"
source = "/3DParts/RatchetPawl/RatchetPawl.scad"
export = [
  "/3DParts/RatchetPawl/RatchetPawl.pdf",
  "/3DParts/RatchetPawl/RatchetPawl.stl"
]
material = "PLA"
printing-process = "FDM"
mass-g = 30
infill = 30
raft-brim = true
supports = false
resolution-mm = 0.3
shell-thickness = 3
top-bottom-thickness = 3

[[part.outer-dimensions]]
openSCAD = "cube(size = [130,20,20]"
unit = "mm"

[[part]]
name = "Ratchet Wheel"
image = "Documentation/Assembly_Guide/Parts_Print_1.jpg"
tsdc = "3DP"
source = "/3DParts/RatchetWheel/RatchetWheel.scad"
export = [
  "/3DParts/RatchetWheel/RatchetWheel.pdf",
  "/3DParts/RatchetWheel/RatchetWheel.stl"
]
material = "PLA"
printing-process = "FDM"
mass-g = 65
infill = 30
raft-brim = true
supports = false
resolution-mm = 0.3
shell-thickness = 3
top-bottom-thickness = 3

[[part.outer-dimensions]]
openSCAD = "cylinder(h=45, r=45)"
unit = "mm"

[[part]]
name = "ScrewSockets"
image = "/Documentation/Assembly_Guide/Parts_Print_6.jpg"
tsdc = "3DP"
source = "/3DParts/ScrewSockets/ScrewSockets.scad"
export = [
  "/3DParts/ScrewSockets/ScrewSockets.pdf",
  "/3DParts/ScrewSockets/ScrewSockets.stl"
]
material = "PLA"
printing-process = "FDM"
mass-g = 5
infill = 30
raft-brim = true
supports = false
resolution-mm = 0.1
shell-thickness = 3
top-bottom-thickness = 8

[[part.outer-dimensions]]
openSCAD = "cylinder(h=12, r=7)"
unit = "mm"

[[part]]
name= "ScrewSockets for ScrewHead"
image = "/Documentation/Assembly_Guide/Parts_Print_5.jpg"
tsdc = "3DP"
source = "/3DParts/ScrewSockets/ScrewSockets.scad"
export = "/3DParts/ScrewSockets/ScrewSocket4ScrewHead.stl"
material = "PLA"
printing-process = "FDM"
mass-g = 5
infill = 30
raft-brim = true
supports = false
resolution-mm = 0.1
shell-thickness = 3
top-bottom-thickness = 8
[[part.outer-dimensions]]
openSCAD = "cylinder(h=12, r=7)"
unit = "mm"

[[part]]
name= "Warpclothbeam 1"
image = "Documentation/Assembly_Guide/Parts_Print_7.jpg"
tsdc = "3DP"
source = "/3DParts/WarpClothBeam/Warpclothbeam_P1.scad"
export = [
  "/3DParts/WarpClothBeam/Warpclothbeam_P1.pdf",
  "/3DParts/WarpClothBeam/Warpclothbeam_1.stl"
]
material = "PLA"
printing-process = "FDM"
mass-g = 65
infill = 30
raft-brim = true
supports = false
resolution-mm = 0.3
shell-thickness = 3
top-bottom-thickness = 3

[[part.outer-dimensions]]
openSCAD = "cylinder(h=163, r=22.5)"
unit = "mm"

[[part]]
name= "Warpclothbeam 2"
image = "Documentation/Assembly_Guide/Parts_Print_7.jpg"
tsdc = "3DP"
source = "/3DParts/WarpClothBeam/Warpclothbeam_P2.scad"
export = [
  "/3DParts/WarpClothBeam/Warpclothbeam_P2.pdf",
  "/3DParts/WarpClothBeam/Warpclothbeam_2.stl"
]
material = "PLA"
printing-process = "FDM"
mass-g = 65
infill = 30
raft-brim = true
supports = false
resolution-mm = 0.3
shell-thickness = 3
top-bottom-thickness = 3

[[part.outer-dimensions]]
openSCAD = "cylinder(h=162, r=22.5)"
unit = "mm"

[[part]]
name= "Warpclothbeam 3"
image = "Documentation/Assembly_Guide/Parts_Print_7.jpg"
tsdc = "3DP"
source = "/3DParts/WarpClothBeam/Warpclothbeam_P3.scad"
export = [
  "/3DParts/WarpClothBeam/Warpclothbeam_P3.pdf",
  "/3DParts/WarpClothBeam/Warpclothbeam_3.stl"
]
material = "PLA"
printing-process = "FDM"
mass-g = 65
infill = 30
raft-brim = true
supports = false
resolution-mm = 0.3
shell-thickness = 3
top-bottom-thickness = 3

[[part.outer-dimensions]]
openSCAD = "cylinder(h=163, r=22.5)"
unit = "mm"

[[part]]
name= "Warpclothbeam 4"
image = "Documentation/Assembly_Guide/Parts_Print_7.jpg"
tsdc = "3DP"
source = "/3DParts/WarpClothBeam/Warpclothbeam_P4.scad"
export = [
  "/3DParts/WarpClothBeam/Warpclothbeam_P4.pdf",
  "/3DParts/WarpClothBeam/Warpclothbeam_4.stl"
]
material = "PLA"
printing-process = "FDM"
mass-g = 60
infill = 30
raft-brim = true
supports = false
resolution-mm = 0.3
shell-thickness = 3
top-bottom-thickness = 3

[[part.outer-dimensions]]
openSCAD = "cylinder(h=140, r=22)"
unit = "mm"

[[part]]
name = "CombHolder"
image = "/Documentation/Assembly_Guide/Parts_CNC_1.jpg"
tsdc = [
  "CNC",
  "COT"
]
source = "/WoodParts/CombHolder/CombHolder.scad"
export = [
  "/WoodParts/CombHolder/CombHolder.pdf",
  "/WoodParts/CombHolder/CombHolder.stl"
]
material = "wood"
mass-kg = "0.16"
smallest-tolerance-class = "IT11"
smallest-inner-radius-mm = 4

[[part.outer-dimensions]]
openSCAD = "cube(size = [118,60,18]"
unit = "mm"

[[part]]
name = "CrossBeam"
image = "/Documentation/Assembly_Guide/Parts_CNC_3.jpg"
tsdc = [
  "CNC",
  "COT"
]
source = "/WoodParts/CrossBeam/CrossBeam.scad"
export = [
  "/WoodParts/CrossBeam/CrossBeam.pdf",
  "/WoodParts/CrossBeam/CrossBeam.stl"
]
material = "wood"
mass-kg = 0.55
smallest-tolerance-class = "IT11"

[[part.outer-dimensions]]
openSCAD = "cube(size = [572,100,20]"
unit = "mm"

[[part]]
name = "Shuttle"
image = "/Documentation/Assembly_Guide/Parts_CNC_6.jpg"
tsdc = [
  "CNC",
  "COT"
]
source = "/WoodParts/Shuttle/Shuttle.scad"
export = [
  "/WoodParts/Shuttle/Shuttle.pdf",
  "/WoodParts/Shuttle/Shuttle.stl"
]
material = "wood"
mass-kg = "0.065"
smallest-tolerance-class = "IT11"
smallest-inner-radius-mm = 4

[[part.outer-dimensions]]
openSCAD = "cube(size = [497,45,6]"
unit = "mm"

[[part]]
name = "SideFrame"
image = "/Documentation/Assembly_Guide/Parts_CNC_2.jpg"
tsdc = [
  "CNC",
  "COT"
]
source = "/WoodParts/SideFrame/SideFrame.scad"
export = [
  "/WoodParts/SideFrame/SideFrame.pdf",
  "/WoodParts/SideFrame/SideFrame.stl"
]
material = "wood"
mass-kg = "0.70"
smallest-tolerance-class = "IT11"
smallest-inner-radius-mm = 4

[[part.outer-dimensions]]
openSCAD = "cube(size = [580,140,18]"
unit = "mm"

[[part]]
name = "SlotBeam"
image = "/Documentation/Assembly_Guide/Parts_CNC_4.jpg"
tsdc = [
  "CNC",
  "COT"
]
source = "/WoodParts/SlotBeam/SlotBeam.scad"
export = [
  "/WoodParts/SlotBeam/SlotBeam.pdf",
  "/WoodParts/SlotBeam/SlotBeam.stl"
]
material = "wood"
mass-kg = "0.15"
smallest-tolerance-class = "IT11"
smallest-inner-radius-mm = 4

[[part.outer-dimensions]]
openSCAD = "cube(size = [566,24,22]"
unit = "mm"

[[part]]
name = "StringStick"
image = "/Documentation/Assembly_Guide/Parts_CNC_5.jpg"
tsdc = [
  "CNC",
  "COT"
]
source = "/WoodParts/StringStick/StringStick.scad"
export = [
  "/WoodParts/StringStick/StringStick.pdf",
  "/WoodParts/StringStick/StringStick.stl"
]
material = "wood"
mass-kg = "0.035"
smallest-tolerance-class = "IT11"
smallest-inner-radius-mm = 4

[[part.outer-dimensions]]
openSCAD = "cube(size = [560,22,6]"
unit = "mm"

[[part]]
name = "WarpClothBeam"
image = "/Documentation/Assembly_Guide/Parts_Other_1.jpg"
tsdc = [
  "CNC",
  "COT"
]
source = "/WoodParts/WarpClothBeam_NoCNC/WarpClothBeam_Wood_NoCNC.scad"
export = [
  "/WoodParts/WarpClothBeam_NoCNC/WarpClothBeam_Shaft.pdf",
  "/WoodParts/WarpClothBeam_NoCNC/WarpClothBeam_Wood_NoCNC.stl"
]
material = "wood"
mass-kg = "0.33"
smallest-tolerance-class = "IT11"
smallest-inner-radius-mm = 4

[[part.outer-dimensions]]
openSCAD = "cylinder(h=710, r=17.5)"
unit = "mm"
